[api]
addr = "0.0.0.0"
port = 8008
code_life_time = 300
code_length = 6

[server]
addr = "0.0.0.0"
port = 25565
timeout = 20
server_ip = "localhost" # Change or remove before production use!
support_1_19 = false # READ: https://github.com/Andcool-Systems/mc-oauth-rs/issues/1

[server.config]
server_name = "mc-oauth-rs"
protocol = 0
version = "1.21"
auth_url = "https://sessionserver.mojang.com/session/minecraft/hasJoined?username={{NAME}}&serverId={{HASH}}"

[server.status]
description = "§6mc-oauth.andcool.ru"
players_max = 0
players_online = 0
icon_path = "server_icon.png"

[messages]
success = "Hello, §6{{NAME}}§r! Your code is: §a{{CODE}}"
bad_session = "§cFailed to login: Invalid session (Try restarting your game and the launcher)"
using_proxy = "§cYou are using a proxy!"
internal_error = "§cSorry, internal server error occurred"
